### ISSUE TITLE
Inaccurate documentation

### ISSUE THREAD

**Issue by kurtjstrosahl-jlab** [opensciencegrid/xrootd-multiuser#57]
The documentation says that to enable checksuming this line needs to be added to the config:

ofs.ckslib ++ libXrdMultiuser.so

When we attempted that we ended up getting permission denied errors when gfal attempted to checksum files after they had been written to local storage.

gfal-sum https://<hostname>:1094/<path to file> ADLER32

The error xrootd reported:
241105 14:40:00 40588 ofs_chksum: <user>.13:48@<host> Unable to checksum /<path to file>; permission denied

we found that using the * instead of the ++ got around this issue.
ofs.ckslib * libXrdMultiuser.so

**Comment by djw8605** [comment]
Interesting, those have different behaviors that I'm not clear on.  I'll bring it up on a meeting tomorrow I have with xrootd developers.

**Comment by djw8605** [comment]
I think you are right, checking with production servers here, and even in the example config, we are using the *, so I think that's correct.  Thanks for the issue!  Docs fixed in c9df3ec474015581d6480729cae1e21c38452c2f
